function mclPaymentTable(rows,showDocument=false){return rows.length?`<div class="table-wrap"><table><thead><tr>${showDocument?'<th>Document / destinataire</th>':''}<th>Date paiement</th><th>Encaissement</th><th>Moyen</th><th>Montant</th><th>Prise en compte</th><th>Actions</th></tr></thead><tbody>${rows.map(p=>`<tr>${showDocument?`<td><strong>${esc(p.number)}</strong><div class="small muted">${esc(p.client)}</div></td>`:''}<td>${day(p.date)}</td><td>${day(p.collection_date)}</td><td>${esc(p.method)}</td><td class="numeric">${euro(p.cents)}</td><td>${p.excluded?'<span class="badge warm">Supprimée des totaux</span>':p.parent_excluded?'<span class="badge warm">Facture exclue</span>':p.counted?'<span class="badge">Comptabilisée</span>':'<span class="badge subtle">Non comptabilisée</span>'}${p.identical_previous?'<span class="badge warm">Ligne identique conservée</span>':'—'}${p.comment?`<div class="small muted">${esc(p.comment)}</div>`:''}</td><td><div class="row">${btn('Modifier','mcl-edit-payment',`data-id="${p.id}"`,'tiny')}${btn(p.excluded?'Rétablir':'Supprimer','mcl-toggle-payment',`data-id="${p.id}"`,'quiet tiny')}</div></td></tr>`).join('')}</tbody></table></div>`:'<p class="copy-note">Aucune ligne de règlement dans cet export pour ce document.</p>';}

function mclInvoiceView(inv){
  mclContextInvoice=inv.id;
  modal(esc((inv.kind==='credit'?'Avoir ':'Facture ')+inv.number),`<div class="row spread"><span class="badge subtle">Historique MonCabinetLibéral</span>${statusBadge(inv)}</div><div class="details-list" style="margin-top:20px"><div><div class="eyebrow">Destinataire</div><h2>${name(inv.recipient)}</h2><p class="copy-note">${day(inv.date)}</p></div><div><div class="eyebrow">Montant du document</div><h2>${euro(inv.total_cents)}</h2>${inv.kind==='invoice'&&inv.status==='issued'?`<p class="copy-note">Solde réglé de référence : ${euro(inv.paid_cents)}<br>Reste à régler : ${euro(inv.balance_cents)}</p>`:''}</div></div>${inv.related_id?`<p style="margin:16px 0">${btn('Voir la facture d’origine','view-invoice',`data-id="${inv.related_id}"`,'tiny')}</p>`:''}${inv.discrepancy_cents?`<div class="inline-note">Écart à vérifier : ${euro(inv.discrepancy_cents)}. Les règlements retenus totalisent ${euro(inv.counted_cents)}, contre ${euro(inv.paid_cents)} selon le solde de la facture. Les lignes supprimées ou non comptabilisées sont écartées des totaux.</div>`:''}<h3 style="margin:22px 0 12px">Règlements exportés · ${inv.payments.length}</h3>${mclPaymentTable(inv.payments)}${inv.comment?`<p class="mcl-text">${esc(inv.comment)}</p>`:''}<p class="copy-note">Les corrections et suppressions ci-dessous concernent ta comptabilité locale. Le fichier source ne contient ni le détail des prestations, ni l’adresse de facturation, ni le PDF original. Le nom du destinataire ne suffit pas à identifier le dossier patient.</p>${inv.status==='replaced'?'<p class="copy-note">Facture annulée dans MCL. Ses lignes de règlement restent visibles ici ; elles ne sont pas ajoutées au montant réglé des factures actives.</p>':''}`,btn('Modifier la facture','mcl-edit-document',`data-id="${inv.id}"`)+btn(inv.excluded?'Rétablir la facture':'Supprimer la facture','mcl-toggle-document',`data-id="${inv.id}"`,'quiet')+btn('Fermer','close-modal'));
}

function mclAccountingPanel(){
  const m=state.mclAccounting;if(!m?.payments&&!m?.documents)return '';
  return `<section class="card card-pad mcl-section"><div class="row spread"><div><div class="eyebrow">Historique importé</div><h2 style="margin-top:8px">MonCabinetLibéral · ${m.documents} documents</h2></div><a class="btn tiny" href="/api/export/mcl-payments.csv" download>Exporter la source MCL</a></div><p class="copy-note">${m.payments} lignes de règlement conservées. Les soldes de référence ci-dessous suivent les factures et leurs corrections. Les règlements retenus se gèrent dans le tableau suivant.</p><div class="table-wrap"><table><thead><tr><th>Année du document</th><th>Documents</th><th>Net facturé</th><th>Solde réglé de référence</th><th>Reste à régler</th></tr></thead><tbody>${m.years.map(y=>`<tr><td>${esc(y.year)}</td><td>${y.documents}</td><td>${euro(y.total_cents)}</td><td>${euro(y.settled_cents)}</td><td>${euro(y.balance_cents)}</td></tr>`).join('')}</tbody></table></div><details class="mcl-review"><summary>${m.discrepancies.length} factures à vérifier · ${m.identical_rows} lignes identiques conservées</summary><p class="copy-note">Compare les soldes des factures avec les règlements que tu conserves. Clique sur un numéro pour corriger ses lignes.</p>${m.discrepancies.map(d=>`<div class="list-row"><button class="link grow" data-action="view-invoice" data-id="${d.id}">${esc(d.number)}</button><span class="small">Solde réglé ${euro(d.paid_cents)} · retenu ${euro(d.counted_cents)}</span><span class="badge warm">Écart ${euro(d.discrepancy_cents)}</span></div>`).join('')}${!m.discrepancies.length?'<p>Aucun écart entre les soldes et les lignes des factures actives.</p>':''}</details><details class="mcl-review"><summary>${m.standalone_payments.length} règlements sur opérations sans facture</summary><p class="copy-note">L’export contient ces règlements, mais pas le détail de leur opération. Leur prise en compte se règle avec Modifier.</p>${mclPaymentTable(m.standalone_payments)}</details><p class="copy-note">Le CSV MCL contient les lignes originales, y compris celles des factures annulées, les écritures « Avoir » et les écarts. Sa somme brute (${euro(m.raw_payment_cents)}) ne constitue pas un total de recettes validé.</p></section>${mclLedgerPanel()}`;
}

let mclEdit=null,mclContextInvoice=null,mclQuery='',mclPage=0,mclFilter='all';
function mclLedgerPanel(){const m=state.mclAccounting;return `<section class="card card-pad mcl-section"><div class="row spread"><div><div class="eyebrow">Ta comptabilité corrigée</div><h2 style="margin-top:8px">Règlements retenus · ${euro(m.counted_cents)}</h2></div><a class="btn primary tiny" href="/api/export/mcl-corrected.csv" download>Exporter les règlements retenus</a></div><p class="copy-note">${m.counted_payments} règlements comptabilisés. Supprimer une ligne la retire des totaux et de cet export ; tu peux la rétablir. Les soldes des factures au-dessus restent une référence distincte.</p><p class="copy-note">Par défaut, les règlements des factures actives sont comptés. Ceux des factures annulées, les écritures Avoir et les opérations sans facture ne le sont pas. Tu peux modifier ce choix sur chaque ligne.</p><div class="toolbar"><input class="input" id="mcl-search" aria-label="Rechercher un règlement" placeholder="Numéro, destinataire, date, moyen…" value="${esc(mclQuery)}"><select id="mcl-filter" aria-label="Filtrer les règlements">${[['all','Toutes les lignes'],['counted','Comptabilisées'],['excluded','Supprimées'],['ignored','Non comptabilisées']].map(([k,v])=>`<option value="${k}" ${mclFilter===k?'selected':''}>${v}</option>`).join('')}</select></div><div id="mcl-ledger-results">${mclLedgerRows()}</div>${m.excluded_documents.length?`<details class="mcl-review"><summary>Factures supprimées des totaux · ${m.excluded_documents.length}</summary>${m.excluded_documents.map(d=>`<div class="list-row"><span class="grow">${esc(d.number)} · ${name(d.recipient)}</span>${btn('Modifier','mcl-edit-document',`data-id="${d.id}"`,'tiny')}${btn('Rétablir','mcl-toggle-document',`data-id="${d.id}"`,'tiny')}</div>`).join('')}</details>`:''}</section>`;}

function mclLedgerRows(){
  const q=mclQuery.toLocaleLowerCase('fr');const rows=state.mclAccounting.payments_rows.filter(p=>(p.number+' '+p.client+' '+p.date+' '+p.method+' '+p.comment).toLocaleLowerCase('fr').includes(q)&&(mclFilter==='all'||(mclFilter==='counted'?p.counted:mclFilter==='excluded'?p.excluded:!p.counted&&!p.excluded)));
  const pages=Math.max(1,Math.ceil(rows.length/30));mclPage=Math.min(mclPage,pages-1);
  return `<div class="row spread" style="margin:14px 0"><span class="small muted">${rows.length} lignes · page ${mclPage+1} / ${pages}</span><div class="row">${btn('Précédent','mcl-page',`data-delta="-1" ${mclPage===0?'disabled':''}`,'tiny')}${btn('Suivant','mcl-page',`data-delta="1" ${mclPage+1>=pages?'disabled':''}`,'tiny')}</div></div>${mclPaymentTable(rows.slice(mclPage*30,mclPage*30+30),true)}`;
}
document.addEventListener('input',e=>{if(e.target.id==='mcl-search'){mclQuery=e.target.value;mclPage=0;$('#mcl-ledger-results').innerHTML=mclLedgerRows();}});
document.addEventListener('change',e=>{if(e.target.id==='mcl-filter'){mclFilter=e.target.value;mclPage=0;$('#mcl-ledger-results').innerHTML=mclLedgerRows();}});

function mclRecord(kind,id){return (kind==='payment'?state.mclAccounting.payments_rows:[...state.invoices,...state.mclAccounting.excluded_documents]).find(r=>r.id===id);}
function mclEditForm(kind,r){
  mclEdit={kind,record:r,context:mclContextInvoice};
  const money=(label,key,value)=>input(label,key,(value/100).toFixed(2),'number','step="0.01" required');
  const fields=kind==='payment'?`${money('Montant (€)','amount',r.cents)}<label class="field">Moyen de paiement<select name="method">${['CB','Chèque','Espèces','Virement','Avoir','Autre'].map(m=>`<option ${r.method===m?'selected':''}>${m}</option>`).join('')}</select></label>${input('Date du paiement','date',r.date,'date','required')}${input('Date d’encaissement','collection_date',r.collection_date,'date')}<label class="check full"><input name="included" type="checkbox" ${r.included?'checked':''}>Comptabiliser ce règlement</label>${r.parent_excluded?'<p class="copy-note full">La facture est supprimée des totaux. Rétablis-la pour que ses règlements puissent compter.</p>':''}`:`${input('Destinataire','recipient_name',r.recipient.last_name,'text','required')}${input('Date du document','date',r.date,'date','required')}${money('Montant du document (€)','amount',r.total_cents)}${money('Reste à régler (€)','balance',r.balance_cents)}<p class="copy-note full">Numéro conservé : ${esc(r.number)}. Le montant du document et ses règlements se corrigent séparément.</p>`;
  modal(kind==='payment'?'Modifier le règlement':'Modifier la facture importée',`<form id="mcl-edit-form"><div class="fields">${fields}<div class="full">${area('Commentaire','comment',r.comment)}</div></div></form>${r.excluded?'<div class="inline-note">Cette ligne est supprimée des totaux. Modifier ses valeurs ne la rétablit pas.</div>':''}<details style="margin-top:16px"><summary>Valeurs de l’import d’origine</summary><p class="copy-note">${day(r.original.date)} · ${euro(kind==='payment'?r.original.cents:r.original.total_cents)}${kind==='payment'?' · '+esc(r.original.method):''}</p>${btn('Réinitialiser à l’import','mcl-reset',`data-kind="${kind}" data-id="${r.id}"`,'tiny')}</details><p class="copy-note">Les modifications sont conservées localement et peuvent être retrouvées dans l’historique.</p>`,btn('Historique','audit-invoice',`data-id="${r.id}"`)+btn('Annuler','close-modal')+btn('Enregistrer','mcl-save','','primary'));
}
function mclReopen(id){const doc=state.invoices.find(d=>d.id===id);if(doc)mclInvoiceView(doc);}
async function mclRefresh(){[state.invoices,state.mclAccounting]=await Promise.all([api('/invoices'),api('/migration/accounting')]);renderAccounting();}
async function runMclAction(action,el){
  if(!el.closest('#modal'))mclContextInvoice=null;
  if(action==='mcl-page'){mclPage+=Number(el.dataset.delta);$('#mcl-ledger-results').innerHTML=mclLedgerRows();return;}
  if(action.startsWith('mcl-edit-')){const kind=action.slice(9);mclEditForm(kind,mclRecord(kind,el.dataset.id));return;}
  if(action==='mcl-save'){
    if(!$('#mcl-edit-form').reportValidity())return;
    const {kind,record:r}=mclEdit;const values=formValues('#mcl-edit-form');
    const toCents=v=>{const n=Number(v);if(!Number.isFinite(n)||Math.abs(n*100-Math.round(n*100))>0.00001)throw new Error('Utilise un montant avec deux décimales maximum.');return Math.round(n*100);};
    let body={version:r.version,date:values.date,comment:values.comment};
    if(kind==='payment')Object.assign(body,{cents:toCents(values.amount),method:values.method,collection_date:values.collection_date,included:values.included==='on'});
    else Object.assign(body,{total_cents:toCents(values.amount),balance_cents:toCents(values.balance),recipient_name:values.recipient_name});
    await api('/accounting/'+kind+'/'+r.id,body);closeModal();await mclRefresh();mclReopen(mclEdit.context);toast('Correction enregistrée. Les totaux et l’export sont à jour.');return;
  }
  if(action.startsWith('mcl-toggle-')||action==='mcl-reset'){
    const kind=action==='mcl-reset'?el.dataset.kind:action.slice(11);const r=mclRecord(kind,el.dataset.id);
    const operation=action==='mcl-reset'?'reset':r.excluded?'restore':'exclude';
    await api('/accounting/'+kind+'/'+r.id,{version:r.version,action:operation});closeModal();await mclRefresh();mclReopen(mclContextInvoice);toast(operation==='exclude'?'Ligne retirée des totaux. Tu peux la rétablir.':operation==='reset'?'Valeurs d’origine rétablies.':'Ligne rétablie.');return;
  }
}

function renderOrphans(){
  const rows=state.orphans||[];
  shell(`<div class="page-head"><div><div class="eyebrow">Reprise MonCabinetLibéral</div><h1 style="margin-top:8px">Consultations orphelines</h1><p>${rows.length} consultations à identifier à partir de leurs notes.</p></div><button class="btn" data-nav="accounting">Voir la comptabilité</button></div><div class="inline-note" style="margin-bottom:24px">Ces notes n’ont aucun rendez-vous correspondant dans l’export. Leur patient et leur date sont donc inconnus. Elles sont conservées intégralement ; aucun dossier n’a été choisi automatiquement.</div><div class="stack">${rows.map((r,i)=>`<article class="card card-pad orphan-card"><div class="row spread"><h2>Consultation ${i+1}</h2><span class="badge warm">À identifier</span></div><p class="copy-note">Référence MCL : ${esc(r.source_id)} · Date inconnue · Patient inconnu</p>${r.fields.map(f=>`<section class="orphan-field"><h3>${esc(f.label)}</h3><div class="mcl-text">${esc(f.value)}</div></section>`).join('')}</article>`).join('')||empty('Aucune consultation orpheline','Toutes les notes importées ont un rendez-vous correspondant.')}<p class="copy-note">Pièces jointes : ajout manuel ultérieur, comme convenu.</p></div>`);
}
